/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools + Templates
 * and open the template in the editor.
 */
package org.winardiaris.uangku;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author ars
 */
public class FormEdit extends javax.swing.JFrame {

    /**
     * Creates new form FormEdit
     */
    public FormEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Ttype = new javax.swing.JComboBox();
        Tdate = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        Tvalue = new javax.swing.JTextField();
        Ljumlah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ttoken = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tdesc = new javax.swing.JTextArea();
        Bsave = new javax.swing.JButton();
        Bcancel = new javax.swing.JButton();
        Luid = new javax.swing.JLabel();
        Ldid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Jenis Keuangan");

        Ttype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debet", "Kredit" }));
        Ttype.setName("Ftype"); // NOI18N

        jLabel3.setText("Tanggal");

        Tvalue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Ljumlah.setText("Jumlah");

        jLabel2.setText("No. Bukti");

        Ttoken.setName("Ftoken"); // NOI18N

        jLabel4.setText("Keterangan");

        Tdesc.setColumns(20);
        Tdesc.setRows(5);
        jScrollPane1.setViewportView(Tdesc);

        Bsave.setText("Perbaharui");
        Bsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BsaveMouseClicked(evt);
            }
        });

        Bcancel.setText("Keluar");
        Bcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BcancelMouseClicked(evt);
            }
        });

        Luid.setText("UID");

        Ldid.setText("DID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tvalue)
                    .addComponent(Ttoken)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Luid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ldid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bcancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Ljumlah)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(Ttype, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(Tdate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(Ljumlah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ttoken, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Bsave)
                        .addComponent(Ldid)
                        .addComponent(Luid))
                    .addComponent(Bcancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BsaveMouseClicked
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date date = Tdate.getDate();
        getDataURL dataurl = new getDataURL();
        String base_url = dataurl.getUrlBase();
        
        String UID = Luid.getText();
        String did  = Ldid.getText();
        String type = Ttype.getSelectedItem().toString();
        String converted_type;
        String converted_date = formatter.format(date);
        String token = Ttoken.getText();
        String tokens = null;
        try {
            tokens = URLEncoder.encode(token, "UTF-8");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(FormData.class.getName()).log(Level.SEVERE, null, ex);
        }
        String value = Tvalue.getText();
        String desc =  Tdesc.getText();
        String descs = null;
        try {
            descs = URLEncoder.encode(desc, "UTF-8");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(FormData.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if("Debet".equals(type)){
            converted_type = "in";
        }
        else{
            converted_type = "out";
        }
        
        System.out.println("type : "+converted_type);
        System.out.println("date : "+converted_date);
        System.out.println("value : "+value);
        System.out.println("token : "+token);
        System.out.println("desc : "+desc);
        
        String url = base_url+"?op=updatedata&uid="+UID+"&did="+did+"&date="+converted_date+"&token="+tokens+"&type="+converted_type+"&value="+value+"&desc="+descs;
        System.out.println(url);
        String data;
        
        try {
            data = dataurl.getData(url);
            System.out.println(data);
            
            if("1".equals(data)){
                JOptionPane.showMessageDialog(this,"Data berhasi disimpan","Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"data gagal disimpan","Informasi",JOptionPane.ERROR_MESSAGE);
                Tdate.setFocusable(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(FormData.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BsaveMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        getDataURL dataurl = new getDataURL();
        String base_url = dataurl.getUrlBase();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        JSONParser parser = new JSONParser();
        String[] titles   = this.getTitle().split("/");
        String uid = titles[0];
        String did = titles[1];
        String url = base_url+"?op=viewdata&uid="+uid+"&did="+did;
        
        String datajson;
        try {
            datajson = dataurl.getData(url);
            Object obj=JSONValue.parse(datajson);
            JSONArray array=(JSONArray)obj;
            int banyak = array.size();
            System.out.println("banyak data:"+banyak);
            for(int i=0;i<banyak;i++){
                JSONObject data=(JSONObject)array.get(i);
                Object did_ = data.get("did");
                Object uid_ = data.get("uid"); 
                Date dates_ = null;
                Object dates = data.get("date");
                Object token = data.get("token");
                Object type = data.get("type");
                Object value = data.get("value");
                Object desc = data.get("desc");
                Object status = data.get("status");
                Object c_at = data.get("c_at");
                Object u_at = data.get("u_at");
            
            
                Luid.setText(uid);
                Ldid.setText(did);
                Tvalue.setText((String) value);
                Ttoken.setText((String) token);
                Tdesc.setText((String) desc);
                if("in".equals(type)){
                   Ttype.setSelectedItem("Debet");
                }
                else{
                  Ttype.setSelectedItem("Kredit");
                }
                try {
                    dates_ = formatter.parse((String) dates);
                    System.out.println(dates);
                    Tdate.setDate(dates_);
                } catch (ParseException ex) {
                    Logger.getLogger(FormEdit.class.getName()).log(Level.SEVERE, null, ex);
                }

                System.out.println("formedit===========");
                System.out.println("uid: "+uid);
                System.out.println("did: "+did);
                System.out.println("token: "+token);
                System.out.println("date: "+dates_);
                System.out.println("desc: "+desc);
                System.out.println("value: "+value);
                System.out.println("type: "+type);
            }         
        } catch (IOException ex) {
            Logger.getLogger(FormEdit.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_formWindowActivated

    private void BcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcancelMouseClicked
       this.dispose();
       FormData fdata = new FormData();
       fdata.setTitle(Luid.getText());
       fdata.setLocationRelativeTo(null);
       fdata.setVisible(true);
    }//GEN-LAST:event_BcancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcancel;
    private javax.swing.JButton Bsave;
    private javax.swing.JLabel Ldid;
    private javax.swing.JLabel Ljumlah;
    private javax.swing.JLabel Luid;
    private org.jdesktop.swingx.JXDatePicker Tdate;
    private javax.swing.JTextArea Tdesc;
    private javax.swing.JTextField Ttoken;
    private javax.swing.JComboBox Ttype;
    private javax.swing.JTextField Tvalue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
